blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://dashfy.dev/discord
    about: Join the Dashfy Discord community to get help, share your feedback, and stay updated on the project
